apiVersion: v1
kind: Secret
metadata:
  name: inventrack-secrets
  namespace: inventrack-prod
type: Opaque
stringData:
  mysql-root-password: "CHANGE_ME_DB_PASSWORD"
  jwt-secret: "CHANGE_ME_JWT_SECRET"
  groq-api-key: "CHANGE_ME_GROQ_API_KEY"
