apiVersion: v1
kind: Secret
metadata:
  name: inventrack-secrets
  namespace: inventrack-prod
type: Opaque
stringData:
  mysql-root-password: "miContra123!"
  jwt-secret: "MiSecretoJwtMuyFuerte2026!"
  groq-api-key: "ABCDEFG1234567890"
